/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AliasRouteImport } from './routes/$alias'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ExperiencesRouteImport } from './routes/experiences'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ChannelSlugRouteImport } from './routes/channel/$slug'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as PlayerIdRouteImport } from './routes/player/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDeskUploadRouteImport } from './routes/api/desk/upload'
import { Route as ApiSsoConsumeRouteImport } from './routes/api/sso/consume'
import { Route as ApiSsoLoginRouteImport } from './routes/api/sso/login'
import { Route as ApiSsoLogoutRouteImport } from './routes/api/sso/logout'
import { Route as ApiSsoMeRouteImport } from './routes/api/sso/me'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasRoute = AliasRouteImport.update({
  id: '/$alias',
  path: '/$alias',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesRoute = ExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelSlugRoute = ChannelSlugRouteImport.update({
  id: '/channel/$slug',
  path: '/channel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskUploadRoute = ApiDeskUploadRouteImport.update({
  id: '/api/desk/upload',
  path: '/api/desk/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoConsumeRoute = ApiSsoConsumeRouteImport.update({
  id: '/api/sso/consume',
  path: '/api/sso/consume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoLoginRoute = ApiSsoLoginRouteImport.update({
  id: '/api/sso/login',
  path: '/api/sso/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoLogoutRoute = ApiSsoLogoutRouteImport.update({
  id: '/api/sso/logout',
  path: '/api/sso/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoMeRoute = ApiSsoMeRouteImport.update({
  id: '/api/sso/me',
  path: '/api/sso/me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/about': typeof AboutRoute
  '/desk': typeof DeskRoute
  '/experiences': typeof ExperiencesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/channel/$slug': typeof ChannelSlugRoute
  '/player/$id': typeof PlayerIdRoute
  '/player/': typeof PlayerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desk/upload': typeof ApiDeskUploadRoute
  '/api/sso/consume': typeof ApiSsoConsumeRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/logout': typeof ApiSsoLogoutRoute
  '/api/sso/me': typeof ApiSsoMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/about': typeof AboutRoute
  '/desk': typeof DeskRoute
  '/experiences': typeof ExperiencesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/channel/$slug': typeof ChannelSlugRoute
  '/player/$id': typeof PlayerIdRoute
  '/player': typeof PlayerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desk/upload': typeof ApiDeskUploadRoute
  '/api/sso/consume': typeof ApiSsoConsumeRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/logout': typeof ApiSsoLogoutRoute
  '/api/sso/me': typeof ApiSsoMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$alias': typeof AliasRoute
  '/about': typeof AboutRoute
  '/desk': typeof DeskRoute
  '/experiences': typeof ExperiencesRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/channel/$slug': typeof ChannelSlugRoute
  '/player/$id': typeof PlayerIdRoute
  '/player/': typeof PlayerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/desk/upload': typeof ApiDeskUploadRoute
  '/api/sso/consume': typeof ApiSsoConsumeRoute
  '/api/sso/login': typeof ApiSsoLoginRoute
  '/api/sso/logout': typeof ApiSsoLogoutRoute
  '/api/sso/me': typeof ApiSsoMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$alias'
    | '/about'
    | '/desk'
    | '/experiences'
    | '/library'
    | '/login'
    | '/logout'
    | '/channel/$slug'
    | '/player/$id'
    | '/player/'
    | '/api/auth/$'
    | '/api/desk/upload'
    | '/api/sso/consume'
    | '/api/sso/login'
    | '/api/sso/logout'
    | '/api/sso/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$alias'
    | '/about'
    | '/desk'
    | '/experiences'
    | '/library'
    | '/login'
    | '/logout'
    | '/channel/$slug'
    | '/player/$id'
    | '/player'
    | '/api/auth/$'
    | '/api/desk/upload'
    | '/api/sso/consume'
    | '/api/sso/login'
    | '/api/sso/logout'
    | '/api/sso/me'
  id:
    | '__root__'
    | '/'
    | '/$alias'
    | '/about'
    | '/desk'
    | '/experiences'
    | '/library'
    | '/login'
    | '/logout'
    | '/channel/$slug'
    | '/player/$id'
    | '/player/'
    | '/api/auth/$'
    | '/api/desk/upload'
    | '/api/sso/consume'
    | '/api/sso/login'
    | '/api/sso/logout'
    | '/api/sso/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliasRoute: typeof AliasRoute
  AboutRoute: typeof AboutRoute
  DeskRoute: typeof DeskRoute
  ExperiencesRoute: typeof ExperiencesRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ChannelSlugRoute: typeof ChannelSlugRoute
  PlayerIdRoute: typeof PlayerIdRoute
  PlayerIndexRoute: typeof PlayerIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDeskUploadRoute: typeof ApiDeskUploadRoute
  ApiSsoConsumeRoute: typeof ApiSsoConsumeRoute
  ApiSsoLoginRoute: typeof ApiSsoLoginRoute
  ApiSsoLogoutRoute: typeof ApiSsoLogoutRoute
  ApiSsoMeRoute: typeof ApiSsoMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$alias': {
      id: '/$alias'
      path: '/$alias'
      fullPath: '/$alias'
      preLoaderRoute: typeof AliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences': {
      id: '/experiences'
      path: '/experiences'
      fullPath: '/experiences'
      preLoaderRoute: typeof ExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel/$slug': {
      id: '/channel/$slug'
      path: '/channel/$slug'
      fullPath: '/channel/$slug'
      preLoaderRoute: typeof ChannelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk/upload': {
      id: '/api/desk/upload'
      path: '/api/desk/upload'
      fullPath: '/api/desk/upload'
      preLoaderRoute: typeof ApiDeskUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/consume': {
      id: '/api/sso/consume'
      path: '/api/sso/consume'
      fullPath: '/api/sso/consume'
      preLoaderRoute: typeof ApiSsoConsumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/login': {
      id: '/api/sso/login'
      path: '/api/sso/login'
      fullPath: '/api/sso/login'
      preLoaderRoute: typeof ApiSsoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/logout': {
      id: '/api/sso/logout'
      path: '/api/sso/logout'
      fullPath: '/api/sso/logout'
      preLoaderRoute: typeof ApiSsoLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso/me': {
      id: '/api/sso/me'
      path: '/api/sso/me'
      fullPath: '/api/sso/me'
      preLoaderRoute: typeof ApiSsoMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliasRoute: AliasRoute,
  AboutRoute: AboutRoute,
  DeskRoute: DeskRoute,
  ExperiencesRoute: ExperiencesRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ChannelSlugRoute: ChannelSlugRoute,
  PlayerIdRoute: PlayerIdRoute,
  PlayerIndexRoute: PlayerIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDeskUploadRoute: ApiDeskUploadRoute,
  ApiSsoConsumeRoute: ApiSsoConsumeRoute,
  ApiSsoLoginRoute: ApiSsoLoginRoute,
  ApiSsoLogoutRoute: ApiSsoLogoutRoute,
  ApiSsoMeRoute: ApiSsoMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
